// Generated by gencpp from file esp32_interface/Driveshaft_Encoder.msg
// DO NOT EDIT!


#ifndef ESP32_INTERFACE_MESSAGE_DRIVESHAFT_ENCODER_H
#define ESP32_INTERFACE_MESSAGE_DRIVESHAFT_ENCODER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace esp32_interface
{
template <class ContainerAllocator>
struct Driveshaft_Encoder_
{
  typedef Driveshaft_Encoder_<ContainerAllocator> Type;

  Driveshaft_Encoder_()
    : header()
    , rpm(0.0)  {
    }
  Driveshaft_Encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rpm(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _rpm_type;
  _rpm_type rpm;





  typedef boost::shared_ptr< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Driveshaft_Encoder_

typedef ::esp32_interface::Driveshaft_Encoder_<std::allocator<void> > Driveshaft_Encoder;

typedef boost::shared_ptr< ::esp32_interface::Driveshaft_Encoder > Driveshaft_EncoderPtr;
typedef boost::shared_ptr< ::esp32_interface::Driveshaft_Encoder const> Driveshaft_EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator1> & lhs, const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rpm == rhs.rpm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator1> & lhs, const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esp32_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "969d40cbc057e12ae62971e22a31432d";
  }

  static const char* value(const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x969d40cbc057e12aULL;
  static const uint64_t static_value2 = 0xe62971e22a31432dULL;
};

template<class ContainerAllocator>
struct DataType< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esp32_interface/Driveshaft_Encoder";
  }

  static const char* value(const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 rpm\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rpm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Driveshaft_Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esp32_interface::Driveshaft_Encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rpm: ";
    Printer<float>::stream(s, indent + "  ", v.rpm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESP32_INTERFACE_MESSAGE_DRIVESHAFT_ENCODER_H
