// Generated by gencpp from file esp32_interface/PWM_Cmd.msg
// DO NOT EDIT!


#ifndef ESP32_INTERFACE_MESSAGE_PWM_CMD_H
#define ESP32_INTERFACE_MESSAGE_PWM_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace esp32_interface
{
template <class ContainerAllocator>
struct PWM_Cmd_
{
  typedef PWM_Cmd_<ContainerAllocator> Type;

  PWM_Cmd_()
    : header()
    , time(0)
    , steer(0)
    , speed(0)  {
    }
  PWM_Cmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time(0)
    , steer(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _time_type;
  _time_type time;

   typedef int64_t _steer_type;
  _steer_type steer;

   typedef int64_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::esp32_interface::PWM_Cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esp32_interface::PWM_Cmd_<ContainerAllocator> const> ConstPtr;

}; // struct PWM_Cmd_

typedef ::esp32_interface::PWM_Cmd_<std::allocator<void> > PWM_Cmd;

typedef boost::shared_ptr< ::esp32_interface::PWM_Cmd > PWM_CmdPtr;
typedef boost::shared_ptr< ::esp32_interface::PWM_Cmd const> PWM_CmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esp32_interface::PWM_Cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esp32_interface::PWM_Cmd_<ContainerAllocator1> & lhs, const ::esp32_interface::PWM_Cmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time == rhs.time &&
    lhs.steer == rhs.steer &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esp32_interface::PWM_Cmd_<ContainerAllocator1> & lhs, const ::esp32_interface::PWM_Cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esp32_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esp32_interface::PWM_Cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_interface::PWM_Cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_interface::PWM_Cmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26db9407d8bd3b856d1f82193033664c";
  }

  static const char* value(const ::esp32_interface::PWM_Cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26db9407d8bd3b85ULL;
  static const uint64_t static_value2 = 0x6d1f82193033664cULL;
};

template<class ContainerAllocator>
struct DataType< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esp32_interface/PWM_Cmd";
  }

  static const char* value(const ::esp32_interface::PWM_Cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int64 time\n"
"int64 steer\n"
"int64 speed\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::esp32_interface::PWM_Cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.steer);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PWM_Cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esp32_interface::PWM_Cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esp32_interface::PWM_Cmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
    s << indent << "steer: ";
    Printer<int64_t>::stream(s, indent + "  ", v.steer);
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESP32_INTERFACE_MESSAGE_PWM_CMD_H
