// Generated by gencpp from file esp32_interface/Car_Control.msg
// DO NOT EDIT!


#ifndef ESP32_INTERFACE_MESSAGE_CAR_CONTROL_H
#define ESP32_INTERFACE_MESSAGE_CAR_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace esp32_interface
{
template <class ContainerAllocator>
struct Car_Control_
{
  typedef Car_Control_<ContainerAllocator> Type;

  Car_Control_()
    : header()
    , desired_steering_angle(0.0)
    , desired_acceleration(0.0)
    , desired_speed(0.0)  {
    }
  Car_Control_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , desired_steering_angle(0.0)
    , desired_acceleration(0.0)
    , desired_speed(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _desired_steering_angle_type;
  _desired_steering_angle_type desired_steering_angle;

   typedef float _desired_acceleration_type;
  _desired_acceleration_type desired_acceleration;

   typedef float _desired_speed_type;
  _desired_speed_type desired_speed;





  typedef boost::shared_ptr< ::esp32_interface::Car_Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esp32_interface::Car_Control_<ContainerAllocator> const> ConstPtr;

}; // struct Car_Control_

typedef ::esp32_interface::Car_Control_<std::allocator<void> > Car_Control;

typedef boost::shared_ptr< ::esp32_interface::Car_Control > Car_ControlPtr;
typedef boost::shared_ptr< ::esp32_interface::Car_Control const> Car_ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esp32_interface::Car_Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esp32_interface::Car_Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esp32_interface::Car_Control_<ContainerAllocator1> & lhs, const ::esp32_interface::Car_Control_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.desired_steering_angle == rhs.desired_steering_angle &&
    lhs.desired_acceleration == rhs.desired_acceleration &&
    lhs.desired_speed == rhs.desired_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esp32_interface::Car_Control_<ContainerAllocator1> & lhs, const ::esp32_interface::Car_Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esp32_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::esp32_interface::Car_Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esp32_interface::Car_Control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_interface::Car_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_interface::Car_Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_interface::Car_Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_interface::Car_Control_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esp32_interface::Car_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f9b642cbe95f516badef7111c9048be";
  }

  static const char* value(const ::esp32_interface::Car_Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f9b642cbe95f516ULL;
  static const uint64_t static_value2 = 0xbadef7111c9048beULL;
};

template<class ContainerAllocator>
struct DataType< ::esp32_interface::Car_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esp32_interface/Car_Control";
  }

  static const char* value(const ::esp32_interface::Car_Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esp32_interface::Car_Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 desired_steering_angle\n"
"float32 desired_acceleration\n"
"float32 desired_speed\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::esp32_interface::Car_Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esp32_interface::Car_Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.desired_steering_angle);
      stream.next(m.desired_acceleration);
      stream.next(m.desired_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Car_Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esp32_interface::Car_Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esp32_interface::Car_Control_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "desired_steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.desired_steering_angle);
    s << indent << "desired_acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.desired_acceleration);
    s << indent << "desired_speed: ";
    Printer<float>::stream(s, indent + "  ", v.desired_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESP32_INTERFACE_MESSAGE_CAR_CONTROL_H
