// Generated by gencpp from file esp32_interface/PWM_Measure.msg
// DO NOT EDIT!


#ifndef ESP32_INTERFACE_MESSAGE_PWM_MEASURE_H
#define ESP32_INTERFACE_MESSAGE_PWM_MEASURE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace esp32_interface
{
template <class ContainerAllocator>
struct PWM_Measure_
{
  typedef PWM_Measure_<ContainerAllocator> Type;

  PWM_Measure_()
    : header()
    , time(0)
    , status(0)
    , control(0)
    , steer(0)
    , speed(0)  {
    }
  PWM_Measure_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time(0)
    , status(0)
    , control(0)
    , steer(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _time_type;
  _time_type time;

   typedef int64_t _status_type;
  _status_type status;

   typedef int64_t _control_type;
  _control_type control;

   typedef int64_t _steer_type;
  _steer_type steer;

   typedef int64_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::esp32_interface::PWM_Measure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esp32_interface::PWM_Measure_<ContainerAllocator> const> ConstPtr;

}; // struct PWM_Measure_

typedef ::esp32_interface::PWM_Measure_<std::allocator<void> > PWM_Measure;

typedef boost::shared_ptr< ::esp32_interface::PWM_Measure > PWM_MeasurePtr;
typedef boost::shared_ptr< ::esp32_interface::PWM_Measure const> PWM_MeasureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esp32_interface::PWM_Measure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esp32_interface::PWM_Measure_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esp32_interface::PWM_Measure_<ContainerAllocator1> & lhs, const ::esp32_interface::PWM_Measure_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time == rhs.time &&
    lhs.status == rhs.status &&
    lhs.control == rhs.control &&
    lhs.steer == rhs.steer &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esp32_interface::PWM_Measure_<ContainerAllocator1> & lhs, const ::esp32_interface::PWM_Measure_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esp32_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::esp32_interface::PWM_Measure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esp32_interface::PWM_Measure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_interface::PWM_Measure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esp32_interface::PWM_Measure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_interface::PWM_Measure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esp32_interface::PWM_Measure_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esp32_interface::PWM_Measure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "267f2594368e6782659d77c294397d6f";
  }

  static const char* value(const ::esp32_interface::PWM_Measure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x267f2594368e6782ULL;
  static const uint64_t static_value2 = 0x659d77c294397d6fULL;
};

template<class ContainerAllocator>
struct DataType< ::esp32_interface::PWM_Measure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esp32_interface/PWM_Measure";
  }

  static const char* value(const ::esp32_interface::PWM_Measure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esp32_interface::PWM_Measure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int64 time\n"
"int64 status\n"
"int64 control\n"
"int64 steer\n"
"int64 speed\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::esp32_interface::PWM_Measure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esp32_interface::PWM_Measure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.status);
      stream.next(m.control);
      stream.next(m.steer);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PWM_Measure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esp32_interface::PWM_Measure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esp32_interface::PWM_Measure_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
    s << indent << "status: ";
    Printer<int64_t>::stream(s, indent + "  ", v.status);
    s << indent << "control: ";
    Printer<int64_t>::stream(s, indent + "  ", v.control);
    s << indent << "steer: ";
    Printer<int64_t>::stream(s, indent + "  ", v.steer);
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESP32_INTERFACE_MESSAGE_PWM_MEASURE_H
