(cl:in-package ui_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          ITOW-VAL
          ITOW
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MIN-VAL
          MIN
          SEC-VAL
          SEC
          VALID-VAL
          VALID
          VALID_DATE-VAL
          VALID_DATE
          VALID_TIME-VAL
          VALID_TIME
          VALID_FULLY_RESOLVED-VAL
          VALID_FULLY_RESOLVED
          VALID_MAG-VAL
          VALID_MAG
          NANO-VAL
          NANO
          GPSFIX-VAL
          GPSFIX
          FLAGS-VAL
          FLAGS
          FLAGS_GNSS_FIX_OK-VAL
          FLAGS_GNSS_FIX_OK
          FLAGS_DIFF_SOLN-VAL
          FLAGS_DIFF_SOLN
          FLAGS_WKN_SET-VAL
          FLAGS_WKN_SET
          FLAGS_TOW_SET-VAL
          FLAGS_TOW_SET
          FLAGS_HEAD_VEH_VALID-VAL
          FLAGS_HEAD_VEH_VALID
          RESERVED0-VAL
          RESERVED0
          LON-VAL
          LON
          LAT-VAL
          LAT
          HEIGHT-VAL
          HEIGHT
          HMSL-VAL
          HMSL
          GSPEED-VAL
          GSPEED
          SPEED-VAL
          SPEED
          HEADMOT-VAL
          HEADMOT
          HEADVEH-VAL
          HEADVEH
          HACC-VAL
          HACC
          VACC-VAL
          VACC
          SACC-VAL
          SACC
          HEADACC-VAL
          HEADACC
          RESERVED1-VAL
          RESERVED1
))